from typing import Protocol


class Player(Protocol):
    async def play(self, source: str, volume: int = 100, loop: bool = False) -> None: ...

    async def set_volume(self, volume: int) -> None: ...

    async def stop(self) -> None: ...

    def running(self) -> bool: ...
